# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build"
        default: master
        required: true
        type: string
      stage:
        description: 'Deploy to stage'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - qa
        - prod

jobs:


  deploy_one:
    if: ${{ ! failure() && ! cancelled() && github.event.inputs.target != 'ALL' }}
    needs: version_one
    uses: ./.github/workflows/deploy_template.yaml
    with:
      branch: ${{ github.event.inputs.branch }}
      stage: ${{ github.event.inputs.stage }}
